services:

  mysql:
    image: mariadb:10.3
    volumes:
    - ./data/db:/var/lib/mysql
    env_file:
    - .env
    restart: unless-stopped

  app:
    image: snipe/snipe-it:latest
    depends_on:
    - mysql
    volumes:
    - ./data/app:/var/lib/snipeit
    - ./data/logs:/var/www/html/storage/logs
    env_file:
    - .env
    ports:
      - "8080:80"
    restart: unless-stopped

