services:
  app:
    image: snipe/snipe-it:latest
    volumes:
    - ./data/app:/var/lib/snipeit
    - ./data/logs:/var/www/html/storage/logs
    env_file:
    - .env
    ports:
      - "8080:80"
    restart: unless-stopped
  db:
    image: mariadb:5.6
    volumes:
    - ./data/db:/var/lib/mysql
    env_file:
    - .env
    restart: unless-stopped


